version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: 65050816/backend:latest
    ports:
      - "5001:5001"
    networks:
      - app-network
    depends_on:
      database:
        condition: service_healthy
    restart: always
    env_file:
      - ./backend/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: 65050816/frontend:latest
    ports:
      - "3000:80"
    networks:
      - app-network
    env_file:
      - ./frontend/.env
    depends_on:
      backend:
        condition: service_healthy
  
  test:
    build:
      context: ./test
      dockerfile: Dockerfile
    image: 65050816/test:latest
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      backend:
        condition: service_healthy

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: 65050816/database:latest
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/database/sql/testMoviesScript.sql:/docker-entrypoint-initdb.d/testMoviesScript.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD: 1234567890
      MYSQL_DATABASE: MADSS  
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"  
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p1234567890"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
