version: '3.8'

services:
  backend:
    image: 65050816/backend:latest
    ports:
      - "5001:5001"
    networks:
      - app-network
    depends_on:
      database:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  frontend:
    image: 65050816/frontend:latest
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      backend:
        condition: service_healthy
    restart: always

  test:
    image: 65050816/test:latest
    ports:
      - "8080"
    networks:
      - app-network
    depends_on:
      backend:
        condition: service_healthy

  database:
    image: 65050816/database:latest
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/database/sql/testMoviesScript.sql:/docker-entrypoint-initdb.d/testMoviesScript.sql:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p1234567890"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  db_data:

networks:
  app-network:
    driver: bridge