name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: 
    - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull Docker Compose file
        uses: actions/checkout@v2  # This checks out your repository by default

      - name: Pull Docker Images
        run: sudo docker-compose pull
      
      - name: Down old container
        run: sudo docker-compose down
      
      - name: Up new container
        run: sudo docker-compose up
