name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: 
    - completed

jobs:
  deploy:
    runs-on: ec2
    steps:
      - name: Pull Docker Images
        run: sudo docker-compose pull
      
      - name: Down old container
        run: sudo docker-compose down
      
      - name: Up new container
        run: sudo docker-compose up
