name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: 
    - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: test
        run: |
          sudo docker images
          echo "test" >> text
          ls
      
      - uses: actions/checkout@v4

      - name: test
        run: |
          cat docker-compose.yml
          cat docker-compose.build.yml
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker Images
        run: sudo docker-compose -f docker-compose.yml pull
      
      - name: Down old container
        run: sudo docker-compose -f docker-compose.yml down
      
      - name: Up new container
        run: sudo docker-compose -f docker-compose.yml up -d
